"""ASCII pixel maps to run-length SVG rects."""

def rects(art):
    out = []
    for y, row in enumerate(art.strip("\n").split("\n")):
        x = 0
        while x < len(row):
            ch = row[x]
            if ch == ".":
                x += 1
                continue
            run = 1
            while x + run < len(row) and row[x + run] == ch:
                run += 1
            out.append((x, y, run, ch))
            x += run
    return out


def size(art):
    rows = art.strip("\n").split("\n")
    return max(len(r) for r in rows), len(rows)


def svg(art, ink, *, scale=None, w=None, style="", label=""):
    cw, ch = size(art)
    body = "".join(
        f'<rect x="{x}" y="{y}" width="{r}" height="1" fill="{ink[c]}"/>'
        for x, y, r, c in rects(art) if ink.get(c)
    )
    px = f"width: {cw * scale}px; height: {ch * scale}px;" if scale else f"width: {w}px;"
    return (f'<svg viewBox="0 0 {cw} {ch}" style="{px} display: block; image-rendering: pixelated;'
            f'{style}" shape-rendering="crispEdges" role="img" aria-label="{label}">{body}</svg>')


# The helm from the mark, in pixels: cross reinforce, two eye slots, breaths.
HELM = """
.................ddd.
...............cccddd
.............ccccddd.
..........cccccddd...
........ccccccdd.....
......ccccccc........
....KKKKKKKKKKcccc...
...KSSSSSSSSSSK......
..KSSSSSSSSSSSSK.....
..KSSSSSSSSSSSSK.....
..KSSSSSSSSSSSSK.....
..KBBBBBBBBBBBBK.....
..KBBBBBBBBBBBBK.....
..KSSSSSBBSSSSSK.....
..KSEEESBBSEEESK.....
..KSEEESBBSEEESK.....
..KSSSSSBBSSSSSK.....
..KSSSSSBBSSSSSK.....
..KSKSSSBBSSSKSK.....
..KSSSSSBBSSSSSK.....
..KSKSSSBBSSSKSK.....
..KSSSSSBBSSSSSK.....
...KSSSSBBSSSSK......
....KKKKKKKKKK.......
"""

SHIELD = """
KKKKKKKKKKKKKKKK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
KffffffffffffffK
.KffffffffffffK.
.KffffffffffffK.
..KffffffffffK..
..KffffffffffK..
...KffffffffK...
....KffffffK....
.....KffffK.....
......KffK......
.......KK.......
"""

CHARGES = {
    # Early heraldry was geometry: crosses, chevrons, bends, and a few beasts.
    "cross": """
................
......gggg......
......gggg......
......gggg......
..gggggggggggg..
..gggggggggggg..
..gggggggggggg..
......gggg......
......gggg......
......gggg......
......gggg......
""",
    "chevron": """
................
................
.......gg.......
......gggg......
.....gggggg.....
....gg.gg.gg....
...gg...gg.gg...
..gg.....gg.gg..
.gg.......gg.gg.
................
""",
    "bend": """
................
...........gg...
..........gggg..
........gggggg..
......gggggg....
....gggggg......
..gggggg........
..gggg..........
..gg............
................
""",
    "fleur": """
.......gg.......
......gggg......
.....gg.gg......
....gg...gg.....
...gg.....gg....
..ggggggggggg...
....gggggggg....
......gggg......
....gggggggg....
......gggg......
""",
    "pale": """
................
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
......gggg......
""",
    "saltire": """
................
.gg..........gg.
..gg........gg..
...gg......gg...
....gg....gg....
.....gg..gg.....
......gggg......
.....gg..gg.....
....gg....gg....
...gg......gg...
..gg........gg..
.gg..........gg.
""",
}

LANCE = """
..............KK
.............KgK
............KgKK
...........KgKK.
..........KwKK..
.........KwKK...
........KwKK....
.......KwKK.....
......KrKK......
.....KwKK.......
....KwKK........
...KwKK.........
..KwKK..........
.KwKK...........
.KKK............
"""

BARRIER = """
................
..K..........K..
..K..........K..
KKKKKKKKKKKKKKKK
KwwwwwwwwwwwwwwK
KKKKKKKKKKKKKKKK
..K..........K..
..K..........K..
KKKKKKKKKKKKKKKK
KwwwwwwwwwwwwwwK
KKKKKKKKKKKKKKKK
..K..........K..
..K..........K..
..KK........KK..
................
"""

CHAPLET = """
................
.....KKKKKK.....
...KKggggggKK...
..KKgg....ggKK..
..Kgg......ggK..
..Kg........gK..
..Kg........gK..
..Kgg......ggK..
..KKgg....ggKK..
...KKggggggKK...
.....KKKKKK.....
................
"""

PENNON = """
................
..KK............
..KwK...........
..KwKKKKKKKK....
..KwKrrrrrrKK...
..KwKrrrrrrrK...
..KwKrrrrrrK....
..KwKKKKKKK.....
..KwK...........
..KwK...........
..KwK...........
..KwK...........
..KwK...........
..KKK...........
................
"""

CROSSED = """
................
.KK..........KK.
.KgK........KgK.
..KgK......KgK..
...KgK....KgK...
....KgK..KgK....
.....KgKKgK.....
......KrrK......
.....KgKKgK.....
....KgK..KgK....
...KgK....KgK...
..KgK......KgK..
.KgK........KgK.
.KK..........KK.
................
"""


LETTERS = {
    "J": [(7, 0, 3, 12), (0, 11, 10, 3), (0, 8, 3, 6)],
    "O": [(0, 0, 3, 14), (8, 0, 3, 14), (0, 0, 11, 3), (0, 11, 11, 3)],
    "U": [(0, 0, 3, 14), (8, 0, 3, 14), (0, 11, 11, 3)],
    "S": [(0, 0, 11, 3), (0, 0, 3, 8), (0, 5, 11, 3), (8, 5, 3, 9), (0, 11, 11, 3)],
    "T": [(0, 0, 11, 3), (4, 0, 3, 14)],
}


def wordmark(word, plates, *, advance=15, h=20):
    """Pixel letters with off-register plates behind the keyline copy."""
    width = advance * len(word) - (advance - 11)
    body = []
    for dx, dy, colour in plates:
        for i, ch in enumerate(word):
            for x, y, w, hh in LETTERS[ch]:
                body.append(f'<rect x="{i * advance + x + dx}" y="{y + dy}" '
                            f'width="{w}" height="{hh}" fill="{colour}"/>')
    vb_w, vb_h = width + 3, 17
    return (f'<svg viewBox="0 0 {vb_w} {vb_h}" style="height: {h}px; display: block; '
            f'image-rendering: pixelated" shape-rendering="crispEdges" role="img" '
            f'aria-label="{word}">{"".join(body)}</svg>'), vb_w / vb_h
